name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Clojure CLI
      uses: DeLaGuardo/setup-clojure@11.0
      with:
        cli: latest

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install npm dependencies
      run: npm install

    - name: Compile ClojureScript with shadow-cljs
      run: npx shadow-cljs release app

    - name: Run syntax checker
      run: node synx.cjs test/grammar.ebnf test/input-ok.txt

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: synx-build
        path: synx.cjs

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        name: Latest Build
        draft: false
        prerelease: false
        files: synx.cjs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
